// src/app/layout.js
import { Nunito } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";

const nunito = Nunito({ 
  subsets: ["latin"],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata = {
  title: "EcoVibe Tribe",
  description: "Generated by ExploreX",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body 
          suppressHydrationWarning 
          className={`${nunito.className} min-h-screen bg-gradient-to-br from-emerald-50 via-teal-50 to-cyan-50`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}